apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-alertmanager
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath  # or 'standard', depending on what you have
  hostPath:
    path: "/mnt/data"