global:
  resolve_timeout: 5m

route:
  receiver: 'email-me'  # This is the default receiver, used when no route matches
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  routes:
    - match:
        alertname: InstanceDown
      receiver: 'email-me'
    - match:
        alertname: HighMemoryUsage
      receiver: 'email-me'
    - match:
        alertname: HighCPUUsage
      receiver: 'email-me'

receivers:
  - name: 'email-me'
    email_configs:
      - to: 'mehdiseyedebrahimi65@gmail.com'
        from: 'mehdiseyedebrahimi65@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'mehdiseyedebrahimi65@gmail.com'
        auth_password: 'kghyuihpgefmzcha'  # Your Gmail app password
        require_tls: true

  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
