# kubernetes-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-prediction-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stock-prediction
  template:
    metadata:
      labels:
        app: stock-prediction
    spec:
      containers:
      - name: stock-prediction
#       image: {your-docker-registry}/stock-prediction-app:latest
        image: itflocken/stock-prediction-app:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: stock-prediction-service
spec:
  selector:
    app: stock-prediction
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer